# Generated by Django 5.2.7 on 2025-10-29 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studymaterial',
            old_name='url',
            new_name='external_url',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.class'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='file_size',
            field=models.IntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='material_type',
            field=models.CharField(choices=[('notes', 'Notes'), ('video', 'Video'), ('assignment', 'Assignment'), ('quiz', 'Quiz'), ('formula', 'Formula'), ('example', 'Example'), ('theory', 'Theory'), ('pdf', 'PDF'), ('document', 'Document'), ('link', 'Link')], max_length=20),
        ),
    ]
